language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
env:
  matrix:
  - DJANGO=2.1.5
  global:
  - DJANGO_SETTINGS_MODULE='mysite.settings'
  - CODECOV_TOKEN="a8e814d9-19c3-48f3-98ea-0ef43961a892"
addons:
  firefox: latest
before_install:
- pip install -r requirements.txt
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
install:
- npm install
- rm -rf ./staticfiles
- python manage.py collectstatic --noinput
- python manage.py runserver &
script:
- pytest
- npm test
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: TwfLz61kJwSJplMB+9bia5AZiYChfFzIV4WT78SrMHD7aN/a/MRusm8schneStJHHZGcUHMTlrcylmWlW3AoayDO8Z9rzYkg4D40kv+KxDN6no8FU8f5lesbxJUObJvjjXgPotYZwBLEwJ3D0MdyckxvegqfC42GlJ3nlplgRRX+eleRYc3MbX93EDVzUWTuNC274F/CCJ13TlMAIXb1dkeumHpHCOrNin0c9hItQR3hyNNoYzmYZV3MaTjP8Ahnjz4nCqgDjB7vRw8IueVCGY25kip3NOQhCtp23gNL5RN6lQDI54RcWUyRY7iYuhx0RYyNIABI/veQBbYPjYTPPEko4SR0/xvQV5asTt4w/E9ReNGw2DRqiU9svX1TXZyo4JOxpDlwHRQmUF0rcM24AjtELpDCoQ62OsrAXJHuEmaQqG9l1v9iI08cZCxHYVab9O3cgHyqQKhhIO1I8ZDTadzl3F8ekfihiVt6ifdE10qaSbaN9EMWIRwrmF7zKotJnsP8sxU98bi8L1nW/qdUYIDfix6rOBB2NsHr7Htl2GDi/MC4lzTY5fauxVP/9nQk9owcLMCoElYe8ssvzCp9Qn59NrEXF42R2MaW1ph0A1KEX/WHYTEglSKGkVuupyMsdJF18AESPfiecdniVQAGeIZADA2OH3SH2gr1+7MRycs=
  app: tweet-mood
  on:
    repo: kirillzabrodin/tweet_mood
    branch: master
