language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  - DJANGO=2.1.5
#the command below will be invoked to install any dependencies - don't
#have any yet so it is commented out
install:
  - pip install -r requirements.txt

#the command below will manage the testing - set up at present to look at the
# script:
#  - will depend on our testing framework
